import 'dart:typed_data';

import 'package:open_print_tag/open_print_tag.dart';
import 'package:test/test.dart';

void main() {
  late OpenPrintTagParser parser;

  setUpAll(() {
    // Use generated data constants
    parser = OpenPrintTagParser.create();
  });

  group('OpenPrintTagParser', () {
    test('throws FormatException on invalid CBOR payload', () async {
      final Uint8List invalidPayload = Uint8List.fromList(<int>[
        0xFF,
        0xFF,
        0xFF,
      ]);

      await expectLater(
        parser.decode(invalidPayload),
        throwsA(isA<FormatException>()),
      );
    });

    test('throws FormatException on non-map CBOR', () async {
      // CBOR encoding of an array [1, 2, 3] instead of a map
      final Uint8List arrayPayload = Uint8List.fromList(<int>[
        0x83,
        0x01,
        0x02,
        0x03,
      ]);

      await expectLater(
        parser.decode(arrayPayload),
        throwsA(isA<FormatException>()),
      );
    });

    test('demonstrates encode and decode binary payload', () async {
      // Create minimal valid data with meta and main
      const OpenPrintTagData data = OpenPrintTagData(
        main: OpenPrintTagMainData(materialClass: 'FFF', materialType: 'PLA'),
      );

      // Step 1: Encode to binary CBOR payload
      final Uint8List payload = parser.encode(data);
      expect(payload, isNotEmpty);

      // Step 2: The payload can now be wrapped in any NDEF MIME record
      // with type OpenPrintTagConstants.mimeType using your preferred library

      // Step 3: Decode the binary payload
      final OpenPrintTagData result = await parser.decode(payload);

      // Verify parsed data
      expect(result, isNotNull);
      expect(result.meta, isNotNull);
      expect(result.main, isNotNull);
      expect(result.main!.materialClass, 'FFF');
      expect(result.main!.materialType, 'PLA');
    });

    test('demonstrates expected usage pattern', () async {
      // This shows the typical usage:

      // 1. Create parser (synchronous with generated data)
      final OpenPrintTagParser myParser = OpenPrintTagParser.create();

      // 2. Read NFC tag and extract CBOR payload from NDEF MIME record
      // (using any NDEF library of your choice: ndef, ndef_record, etc.)
      // Look for MIME type: OpenPrintTagConstants.mimeType
      // final Uint8List payload = extractPayloadFromNdefRecord(ndefRecords);

      // 3. Decode binary payload (enums are automatically converted)
      // final tagData = await myParser.decode(payload);

      // 4. Use the data
      // print(tagData.main?.materialName);
      // print(tagData.main?.materialType);  // This is a string like "PLA", not a number!

      expect(myParser, isNotNull);

      // Demonstrate encoding:
      const OpenPrintTagData data = OpenPrintTagData(
        main: OpenPrintTagMainData(materialClass: 'FFF', materialType: 'PLA'),
      );

      // 1. Encode to binary CBOR payload
      final Uint8List payload = myParser.encode(data);
      expect(payload, isNotEmpty);

      // 2. Wrap in NDEF MIME record with type OpenPrintTagConstants.mimeType
      // (using any NDEF library of your choice)

      // 3. Write to NFC tag
      // await nfcLib.writeNdefMessage([record]);
    });
  });

  group('OpenPrintTagParser.encode', () {
    test('encodes basic main data without meta region', () {
      const OpenPrintTagData data = OpenPrintTagData(
        main: OpenPrintTagMainData(
          materialClass: 'FFF',
          materialName: 'PLA Premium',
          materialType: 'PLA',
          minPrintTemperature: 215,
          minBedTemperature: 60,
        ),
      );

      final Uint8List payload = parser.encode(data);

      expect(payload, isNotEmpty);
      expect(payload, isA<Uint8List>());
    });

    test('encodes data with meta and aux regions', () {
      const OpenPrintTagData data = OpenPrintTagData(
        meta: OpenPrintTagMetaData(mainRegionOffset: 0, mainRegionSize: 0),
        main: OpenPrintTagMainData(
          materialClass: 'FFF',
          materialName: 'PETG Premium',
          materialType: 'PETG',
          minPrintTemperature: 230,
          minBedTemperature: 85,
        ),
        aux: OpenPrintTagAuxData(workgroup: 'ProdGrp', consumedWeight: 50.5),
      );

      final Uint8List payload = parser.encode(data);

      expect(payload, isNotEmpty);
      expect(payload, isA<Uint8List>());
    });

    test('throws ArgumentError when no main data provided without meta', () {
      const OpenPrintTagData data = OpenPrintTagData();

      expect(() => parser.encode(data), throwsArgumentError);
    });

    test('round-trip: encode then decode produces equivalent data', () async {
      // Create original data
      // Note: meta is automatically generated by encoder per spec
      const OpenPrintTagData originalData = OpenPrintTagData(
        main: OpenPrintTagMainData(
          materialClass: 'FFF',
          materialName: 'ABS Premium',
          materialType: 'ABS',
          minPrintTemperature: 240,
          minBedTemperature: 100,
          density: 1.04,
        ),
      );

      // Encode to binary payload
      final Uint8List payload = parser.encode(originalData);

      // Decode back
      final OpenPrintTagData decodedData = await parser.decode(payload);

      // Verify that main data matches
      expect(decodedData.main, isNotNull);
      expect(decodedData.main!.materialClass, originalData.main!.materialClass);
      expect(decodedData.main!.materialName, originalData.main!.materialName);
      expect(decodedData.main!.materialType, originalData.main!.materialType);
      expect(
        decodedData.main!.minPrintTemperature,
        originalData.main!.minPrintTemperature,
      );
      expect(
        decodedData.main!.minBedTemperature,
        originalData.main!.minBedTemperature,
      );
      expect(decodedData.main!.density, originalData.main!.density);

      // Meta should be present (automatically generated)
      expect(decodedData.meta, isNotNull);
    });

    test('round-trip: encode then decode with meta and aux regions', () async {
      // Create original data with all regions
      const OpenPrintTagData originalData = OpenPrintTagData(
        meta: OpenPrintTagMetaData(),
        main: OpenPrintTagMainData(
          materialClass: 'FFF',
          materialName: 'TPU Flexible',
          materialType: 'TPU',
          minPrintTemperature: 220,
          minBedTemperature: 50,
        ),
        aux: OpenPrintTagAuxData(workgroup: 'TestGrp', consumedWeight: 123.45),
      );

      // Encode to binary payload
      final Uint8List payload = parser.encode(originalData);

      // Decode back
      final OpenPrintTagData decodedData = await parser.decode(payload);

      // Verify all regions
      expect(decodedData.main, isNotNull);
      expect(decodedData.main!.materialClass, originalData.main!.materialClass);
      expect(decodedData.main!.materialName, originalData.main!.materialName);
      expect(decodedData.main!.materialType, originalData.main!.materialType);

      expect(decodedData.aux, isNotNull);
      expect(decodedData.aux!.workgroup, originalData.aux!.workgroup);
      expect(decodedData.aux!.consumedWeight, originalData.aux!.consumedWeight);

      expect(decodedData.meta, isNotNull);
      // Meta offsets will be recalculated, so we don't compare them directly
    });

    test('demonstrates encode usage pattern', () async {
      final OpenPrintTagParser myParser = OpenPrintTagParser.create();

      // Create data - meta section will be automatically generated per spec
      const OpenPrintTagData data = OpenPrintTagData(
        main: OpenPrintTagMainData(
          materialClass: 'FFF',
          materialName: 'My Custom PLA',
          materialType: 'PLA',
          minPrintTemperature: 210,
          minBedTemperature: 60,
        ),
      );

      final Uint8List payload = myParser.encode(data);

      expect(payload, isNotNull);
      expect(payload, isNotEmpty);

      // Verify it can be decoded back
      final OpenPrintTagData decoded = await myParser.decode(payload);
      expect(decoded.meta, isNotNull); // Meta automatically generated
      expect(decoded.main, isNotNull);
    });

    test(
      'throws ArgumentError when required field material_class is missing',
      () {
        const OpenPrintTagData data = OpenPrintTagData(
          main: OpenPrintTagMainData(
            // Missing materialClass (required field)
            materialName: 'PLA Premium',
            materialType: 'PLA',
            minPrintTemperature: 215,
            minBedTemperature: 60,
          ),
        );

        expect(
          () => parser.encode(data),
          throwsA(
            isA<ArgumentError>().having(
              (ArgumentError e) => e.message,
              'message',
              contains('Missing required field: material_class'),
            ),
          ),
        );
      },
    );
  });

  group('Meta region compatibility tests', () {
    test('encoder creates minimal META like Python', () async {
      // Python nfc_initialize creates META with only necessary fields
      // Let's verify our encoder does the same

      const OpenPrintTagData data = OpenPrintTagData(
        main: OpenPrintTagMainData(
          materialClass: 'FFF',
          materialType: 'PLA',
          materialName: 'Test Material',
        ),
      );

      final Uint8List payload = parser.encode(data);
      final OpenPrintTagData decoded = await parser.decode(payload);

      // META should exist
      expect(decoded.meta, isNotNull);

      // main_region_offset should be set (because META size varies)
      expect(decoded.meta!.mainRegionOffset, isNotNull);
      expect(decoded.meta!.mainRegionOffset! > 0, true);

      // main_region_size should NOT be set (optional, decoder calculates it)
      expect(decoded.meta!.mainRegionSize, isNull);

      // aux fields should NOT be set (no aux region)
      expect(decoded.meta!.auxRegionOffset, isNull);
      expect(decoded.meta!.auxRegionSize, isNull);

      print('✅ Minimal META (no aux):');
      print('   main_region_offset: ${decoded.meta!.mainRegionOffset}');
      print('   main_region_size: ${decoded.meta!.mainRegionSize}');
      print('   aux_region_offset: ${decoded.meta!.auxRegionOffset}');
    });

    test('encoder creates META with aux like Python', () async {
      const OpenPrintTagData data = OpenPrintTagData(
        main: OpenPrintTagMainData(materialClass: 'FFF', materialType: 'PLA'),
        aux: OpenPrintTagAuxData(
          workgroup: 'TestGrp', // Max 8 chars
          consumedWeight: 100.5,
        ),
      );

      final Uint8List payload = parser.encode(data);
      final OpenPrintTagData decoded = await parser.decode(payload);

      expect(decoded.meta, isNotNull);
      expect(decoded.meta!.mainRegionOffset, isNotNull);
      expect(decoded.meta!.mainRegionSize, isNull); // Should NOT be set
      expect(decoded.meta!.auxRegionOffset, isNotNull); // Should be set
      expect(decoded.meta!.auxRegionSize, isNull); // Should NOT be set

      print('✅ META with aux:');
      print('   main_region_offset: ${decoded.meta!.mainRegionOffset}');
      print('   main_region_size: ${decoded.meta!.mainRegionSize}');
      print('   aux_region_offset: ${decoded.meta!.auxRegionOffset}');
      print('   aux_region_size: ${decoded.meta!.auxRegionSize}');
    });

    test('validates meta structure matches expected format', () async {
      // Test that encoder creates proper meta structure
      const OpenPrintTagData data = OpenPrintTagData(
        main: OpenPrintTagMainData(
          materialClass: 'FFF',
          materialType: 'PLA',
          materialName: 'Test Material',
        ),
      );

      final Uint8List payload = parser.encode(data);
      final OpenPrintTagData decoded = await parser.decode(payload);

      // Validate meta structure
      expect(decoded.meta, isNotNull);

      // main_region_offset should be set
      expect(decoded.meta!.mainRegionOffset, isNotNull);
      expect(decoded.meta!.mainRegionOffset! > 0, true);

      // Size fields should NOT be set (optional, decoder calculates them)
      expect(decoded.meta!.mainRegionSize, isNull);
      expect(decoded.meta!.auxRegionSize, isNull);

      // No aux region in this test
      expect(decoded.meta!.auxRegionOffset, isNull);

      print('✅ Meta structure valid:');
      print('   main_region_offset: ${decoded.meta!.mainRegionOffset}');
      print('   main_region_size: ${decoded.meta!.mainRegionSize}');
      print('   aux_region_offset: ${decoded.meta!.auxRegionOffset}');
    });
  });
}
