name: open_print_tag
description: Encode and decode OpenPrintTag data to/from CBOR. Stores material
  info like type, temperatures, brand, and more.
version: 0.0.1
repository: https://github.com/prusa3d/OpenPrintTag-dart
environment:
  sdk: ^3.9.2

dependencies:
  cbor: ^6.3.7
  convert: ^3.1.2
  copy_with_extension: ^10.0.1
  crypto: ^3.0.6
  ieee754: ^1.0.3
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  build: ^4.0.1
  build_runner: ^2.9.0
  code_builder: ^4.11.0
  copy_with_extension_gen: ^10.0.1
  dart_style: ^3.1.2
  json_serializable: ^6.11.1
  lints: ^6.0.0
  ndef: ^0.3.4
  test: ^1.26.3
  yaml: ^3.1.3
