// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: data-submodule/data/tags_enum.yaml
import 'tag_categories_enum.enum.g.dart';

enum TagsEnum {
  filtration_recommended(
    key: 0,
    name: 'Filtration recommended',
    category: TagCategoriesEnum.biological,
    implies: null,
    hints: null,
  ),
  biocompatible(
    key: 1,
    name: 'Biocompatible',
    category: TagCategoriesEnum.biological,
    implies: null,
    hints: null,
  ),
  home_compostable(
    key: 61,
    name: 'Home compostable',
    category: TagCategoriesEnum.biological,
    implies: null,
    hints: null,
  ),
  industrially_compostable(
    key: 62,
    name: 'Industrially compostable',
    category: TagCategoriesEnum.biological,
    implies: null,
    hints: null,
  ),
  bio_based(
    key: 63,
    name: 'Bio-based',
    category: TagCategoriesEnum.biological,
    implies: null,
    hints: null,
  ),
  antibacterial(
    key: 2,
    name: 'Antibacterial',
    category: TagCategoriesEnum.biological,
    implies: null,
    hints: null,
  ),
  air_filtering(
    key: 3,
    name: 'Air filtering',
    category: TagCategoriesEnum.biological,
    implies: null,
    hints: null,
  ),
  abrasive(
    key: 4,
    name: 'Abrasive',
    category: TagCategoriesEnum.physical,
    implies: null,
    hints: null,
  ),
  foaming(
    key: 5,
    name: 'Foaming',
    category: TagCategoriesEnum.physical,
    implies: null,
    hints: null,
  ),
  castable(
    key: 67,
    name: 'Castable',
    category: TagCategoriesEnum.physical,
    implies: null,
    hints: null,
  ),
  self_extinguishing(
    key: 6,
    name: 'Self-extinguishing',
    category: TagCategoriesEnum.physical,
    implies: null,
    hints: null,
  ),
  paramagnetic(
    key: 7,
    name: 'Paramagnetic',
    category: TagCategoriesEnum.physical,
    implies: null,
    hints: null,
  ),
  radiation_shielding(
    key: 8,
    name: 'Radiation shielding',
    category: TagCategoriesEnum.physical,
    implies: null,
    hints: null,
  ),
  high_temperature(
    key: 9,
    name: 'High temperature',
    category: TagCategoriesEnum.physical,
    implies: null,
    hints: null,
  ),
  high_speed(
    key: 71,
    name: 'High speed',
    category: TagCategoriesEnum.physical,
    implies: null,
    hints: null,
  ),
  esd_safe(
    key: 10,
    name: 'ESD safe',
    category: TagCategoriesEnum.electrical,
    implies: null,
    hints: null,
  ),
  conductive(
    key: 11,
    name: 'Conductive',
    category: TagCategoriesEnum.electrical,
    implies: null,
    hints: null,
  ),
  emi_shielding(
    key: 70,
    name: 'EMI shielding',
    category: TagCategoriesEnum.electrical,
    implies: const [TagsEnum.conductive],
    hints: null,
  ),
  blend(
    key: 12,
    name: 'Blend',
    category: TagCategoriesEnum.chemical,
    implies: null,
    hints: null,
  ),
  water_soluble(
    key: 13,
    name: 'Water soluble',
    category: TagCategoriesEnum.chemical,
    implies: null,
    hints: null,
  ),
  ipa_soluble(
    key: 14,
    name: 'IPA soluble',
    category: TagCategoriesEnum.chemical,
    implies: null,
    hints: null,
  ),
  limonene_soluble(
    key: 15,
    name: 'Limonene soluble',
    category: TagCategoriesEnum.chemical,
    implies: null,
    hints: null,
  ),
  low_outgassing(
    key: 64,
    name: 'Low outgassing',
    category: TagCategoriesEnum.chemical,
    implies: null,
    hints: null,
  ),
  matte(
    key: 16,
    name: 'Matte',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  silk(
    key: 17,
    name: 'Silk',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  translucent(
    key: 19,
    name: 'Translucent',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  transparent(
    key: 20,
    name: 'Transparent',
    category: TagCategoriesEnum.visual,
    implies: const [TagsEnum.translucent],
    hints: null,
  ),
  without_pigments(
    key: 65,
    name: 'Without pigments',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: const [TagsEnum.translucent],
  ),
  iridescent(
    key: 21,
    name: 'Iridescent',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  pearlescent(
    key: 22,
    name: 'Pearlescent',
    category: TagCategoriesEnum.visual,
    implies: const [TagsEnum.iridescent],
    hints: null,
  ),
  glitter(
    key: 23,
    name: 'Glitter',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  glow_in_the_dark(
    key: 24,
    name: 'Glow in the dark',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  neon(
    key: 25,
    name: 'Neon',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  illuminescent_color_change(
    key: 26,
    name: 'Illuminescent color change',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  temperature_color_change(
    key: 27,
    name: 'Temperature color change',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  gradual_color_change(
    key: 28,
    name: 'Gradual color change',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  coextruded(
    key: 29,
    name: 'Coextruded',
    category: TagCategoriesEnum.visual,
    implies: null,
    hints: null,
  ),
  contains_carbon(
    key: 30,
    name: 'Contains carbon',
    category: TagCategoriesEnum.additives_other,
    implies: null,
    hints: null,
  ),
  contains_carbon_fiber(
    key: 31,
    name: 'Contains carbon fiber',
    category: TagCategoriesEnum.additives_other,
    implies: const [TagsEnum.contains_carbon],
    hints: null,
  ),
  contains_carbon_nano_tubes(
    key: 32,
    name: 'Contains carbon nano tubes',
    category: TagCategoriesEnum.additives_other,
    implies: const [TagsEnum.contains_carbon],
    hints: null,
  ),
  contains_graphene(
    key: 72,
    name: 'Contains graphene',
    category: TagCategoriesEnum.additives_other,
    implies: const [TagsEnum.contains_carbon],
    hints: null,
  ),
  contains_glass(
    key: 33,
    name: 'Contains glass',
    category: TagCategoriesEnum.additives_other,
    implies: null,
    hints: null,
  ),
  contains_glass_fiber(
    key: 34,
    name: 'Contains glass fiber',
    category: TagCategoriesEnum.additives_other,
    implies: const [TagsEnum.contains_glass],
    hints: null,
  ),
  contains_kevlar(
    key: 35,
    name: 'Contains Kevlar',
    category: TagCategoriesEnum.additives_other,
    implies: null,
    hints: null,
  ),
  contains_ptfe(
    key: 68,
    name: 'Contains PTFE',
    category: TagCategoriesEnum.additives_other,
    implies: null,
    hints: null,
  ),
  contains_stone(
    key: 36,
    name: 'Contains stone',
    category: TagCategoriesEnum.additives_other,
    implies: null,
    hints: const [TagsEnum.abrasive],
  ),
  contains_magnetite(
    key: 37,
    name: 'Contains magnetite',
    category: TagCategoriesEnum.additives_other,
    implies: null,
    hints: const [TagsEnum.abrasive],
  ),
  contains_organic_material(
    key: 38,
    name: 'Contains organic material',
    category: TagCategoriesEnum.additives_organic,
    implies: null,
    hints: null,
  ),
  contains_cork(
    key: 39,
    name: 'Contains cork',
    category: TagCategoriesEnum.additives_organic,
    implies: const [TagsEnum.contains_organic_material],
    hints: null,
  ),
  contains_wax(
    key: 40,
    name: 'Contains wax',
    category: TagCategoriesEnum.additives_organic,
    implies: const [TagsEnum.contains_organic_material],
    hints: null,
  ),
  contains_wood(
    key: 41,
    name: 'Contains wood',
    category: TagCategoriesEnum.additives_organic,
    implies: const [TagsEnum.contains_organic_material],
    hints: null,
  ),
  contains_algae(
    key: 66,
    name: 'Contains algae',
    category: TagCategoriesEnum.additives_organic,
    implies: const [TagsEnum.contains_organic_material],
    hints: null,
  ),
  contains_bamboo(
    key: 42,
    name: 'Contains bamboo',
    category: TagCategoriesEnum.additives_organic,
    implies: const [TagsEnum.contains_wood],
    hints: null,
  ),
  contains_pine(
    key: 43,
    name: 'Contains pine',
    category: TagCategoriesEnum.additives_organic,
    implies: const [TagsEnum.contains_wood],
    hints: null,
  ),
  contains_ceramic(
    key: 44,
    name: 'Contains ceramic',
    category: TagCategoriesEnum.additives_other,
    implies: null,
    hints: const [TagsEnum.abrasive],
  ),
  contains_boron_carbide(
    key: 45,
    name: 'Contains boron carbide',
    category: TagCategoriesEnum.additives_other,
    implies: const [TagsEnum.contains_ceramic],
    hints: const [TagsEnum.radiation_shielding],
  ),
  contains_metal(
    key: 46,
    name: 'Contains metal',
    category: TagCategoriesEnum.additives_metal,
    implies: null,
    hints: const [TagsEnum.abrasive],
  ),
  contains_bronze(
    key: 47,
    name: 'Contains bronze',
    category: TagCategoriesEnum.additives_metal,
    implies: const [TagsEnum.contains_metal],
    hints: null,
  ),
  contains_iron(
    key: 48,
    name: 'Contains iron',
    category: TagCategoriesEnum.additives_metal,
    implies: const [TagsEnum.contains_metal],
    hints: null,
  ),
  contains_steel(
    key: 49,
    name: 'Contains steel',
    category: TagCategoriesEnum.additives_metal,
    implies: const [TagsEnum.contains_metal],
    hints: null,
  ),
  contains_silver(
    key: 50,
    name: 'Contains silver',
    category: TagCategoriesEnum.additives_metal,
    implies: const [TagsEnum.contains_metal],
    hints: const [TagsEnum.antibacterial],
  ),
  contains_copper(
    key: 51,
    name: 'Contains copper',
    category: TagCategoriesEnum.additives_metal,
    implies: const [TagsEnum.contains_metal],
    hints: null,
  ),
  contains_aluminium(
    key: 52,
    name: 'Contains aluminium',
    category: TagCategoriesEnum.additives_metal,
    implies: const [TagsEnum.contains_metal],
    hints: null,
  ),
  contains_brass(
    key: 53,
    name: 'Contains brass',
    category: TagCategoriesEnum.additives_metal,
    implies: const [TagsEnum.contains_metal],
    hints: null,
  ),
  contains_tungsten(
    key: 54,
    name: 'Contains tungsten',
    category: TagCategoriesEnum.additives_metal,
    implies: const [TagsEnum.contains_metal],
    hints: const [TagsEnum.radiation_shielding],
  ),
  imitates_wood(
    key: 55,
    name: 'Imitates wood',
    category: TagCategoriesEnum.imitation,
    implies: null,
    hints: null,
  ),
  imitates_metal(
    key: 56,
    name: 'Imitates metal',
    category: TagCategoriesEnum.imitation,
    implies: null,
    hints: null,
  ),
  imitates_marble(
    key: 57,
    name: 'Imitates marble',
    category: TagCategoriesEnum.imitation,
    implies: null,
    hints: null,
  ),
  imitates_stone(
    key: 58,
    name: 'Imitates stone',
    category: TagCategoriesEnum.imitation,
    implies: null,
    hints: null,
  ),
  lithophane(
    key: 59,
    name: 'Lithophane',
    category: TagCategoriesEnum.other,
    implies: null,
    hints: null,
  ),
  recycled(
    key: 60,
    name: 'Recycled',
    category: TagCategoriesEnum.other,
    implies: null,
    hints: null,
  ),
  limited_edition(
    key: 69,
    name: 'Limited edition',
    category: TagCategoriesEnum.other,
    implies: null,
    hints: null,
  );

  final int key;
  final String name;
  final TagCategoriesEnum? category;
  final List<TagsEnum>? implies;
  final List<TagsEnum>? hints;

  const TagsEnum({
    required this.key,
    required this.name,
    this.category,
    this.implies,
    this.hints,
  });

  static TagsEnum byKey(int key) => values.firstWhere((e) => e.key == key);
}
