// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'open_print_tag_main_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OpenPrintTagMainData _$OpenPrintTagMainDataFromJson(
  Map<String, dynamic> json,
) => OpenPrintTagMainData(
  instanceUuid: json['instance_uuid'] as String?,
  packageUuid: json['package_uuid'] as String?,
  materialUuid: json['material_uuid'] as String?,
  brandUuid: json['brand_uuid'] as String?,
  gtin: json['gtin'] as num?,
  brandSpecificInstanceId: json['brand_specific_instance_id'] as String?,
  brandSpecificPackageId: json['brand_specific_package_id'] as String?,
  brandSpecificMaterialId: json['brand_specific_material_id'] as String?,
  materialClass: json['material_class'] as String?,
  materialType: json['material_type'] as String?,
  materialName: json['material_name'] as String?,
  materialAbbreviation: json['material_abbreviation'] as String?,
  brandName: json['brand_name'] as String?,
  writeProtection: json['write_protection'] as String?,
  manufacturedDate: (json['manufactured_date'] as num?)?.toInt(),
  expirationDate: (json['expiration_date'] as num?)?.toInt(),
  nominalNettoFullWeight: json['nominal_netto_full_weight'] as num?,
  actualNettoFullWeight: json['actual_netto_full_weight'] as num?,
  nominalFullLength: json['nominal_full_length'] as num?,
  actualFullLength: json['actual_full_length'] as num?,
  emptyContainerWeight: json['empty_container_weight'] as num?,
  primaryColor: OpenPrintTagMainData._uint8ListFromJson(json['primary_color']),
  secondaryColor0: OpenPrintTagMainData._uint8ListFromJson(
    json['secondary_color_0'],
  ),
  secondaryColor1: OpenPrintTagMainData._uint8ListFromJson(
    json['secondary_color_1'],
  ),
  secondaryColor2: OpenPrintTagMainData._uint8ListFromJson(
    json['secondary_color_2'],
  ),
  secondaryColor3: OpenPrintTagMainData._uint8ListFromJson(
    json['secondary_color_3'],
  ),
  secondaryColor4: OpenPrintTagMainData._uint8ListFromJson(
    json['secondary_color_4'],
  ),
  transmissionDistance: json['transmission_distance'] as num?,
  tags: (json['tags'] as List<dynamic>?)?.map((e) => e as String).toList(),
  density: json['density'] as num?,
  filamentDiameter: json['filament_diameter'] as num?,
  shoreHardnessA: (json['shore_hardness_a'] as num?)?.toInt(),
  shoreHardnessD: (json['shore_hardness_d'] as num?)?.toInt(),
  minNozzleDiameter: json['min_nozzle_diameter'] as num?,
  minPrintTemperature: (json['min_print_temperature'] as num?)?.toInt(),
  maxPrintTemperature: (json['max_print_temperature'] as num?)?.toInt(),
  preheatTemperature: (json['preheat_temperature'] as num?)?.toInt(),
  minBedTemperature: (json['min_bed_temperature'] as num?)?.toInt(),
  maxBedTemperature: (json['max_bed_temperature'] as num?)?.toInt(),
  minChamberTemperature: (json['min_chamber_temperature'] as num?)?.toInt(),
  maxChamberTemperature: (json['max_chamber_temperature'] as num?)?.toInt(),
  chamberTemperature: (json['chamber_temperature'] as num?)?.toInt(),
  containerWidth: (json['container_width'] as num?)?.toInt(),
  containerOuterDiameter: (json['container_outer_diameter'] as num?)?.toInt(),
  containerInnerDiameter: (json['container_inner_diameter'] as num?)?.toInt(),
  containerHoleDiameter: (json['container_hole_diameter'] as num?)?.toInt(),
  viscosity18c: json['viscosity_18c'] as num?,
  viscosity25c: json['viscosity_25c'] as num?,
  viscosity40c: json['viscosity_40c'] as num?,
  viscosity60c: json['viscosity_60c'] as num?,
  containerVolumetricCapacity: json['container_volumetric_capacity'] as num?,
  cureWavelength: (json['cure_wavelength'] as num?)?.toInt(),
);

Map<String, dynamic> _$OpenPrintTagMainDataToJson(
  OpenPrintTagMainData instance,
) => <String, dynamic>{
  'instance_uuid': instance.instanceUuid,
  'package_uuid': instance.packageUuid,
  'material_uuid': instance.materialUuid,
  'brand_uuid': instance.brandUuid,
  'gtin': instance.gtin,
  'brand_specific_instance_id': instance.brandSpecificInstanceId,
  'brand_specific_package_id': instance.brandSpecificPackageId,
  'brand_specific_material_id': instance.brandSpecificMaterialId,
  'material_class': instance.materialClass,
  'material_type': instance.materialType,
  'material_name': instance.materialName,
  'material_abbreviation': instance.materialAbbreviation,
  'brand_name': instance.brandName,
  'write_protection': instance.writeProtection,
  'manufactured_date': instance.manufacturedDate,
  'expiration_date': instance.expirationDate,
  'nominal_netto_full_weight': instance.nominalNettoFullWeight,
  'actual_netto_full_weight': instance.actualNettoFullWeight,
  'nominal_full_length': instance.nominalFullLength,
  'actual_full_length': instance.actualFullLength,
  'empty_container_weight': instance.emptyContainerWeight,
  'primary_color': OpenPrintTagMainData._uint8ListToJson(instance.primaryColor),
  'secondary_color_0': OpenPrintTagMainData._uint8ListToJson(
    instance.secondaryColor0,
  ),
  'secondary_color_1': OpenPrintTagMainData._uint8ListToJson(
    instance.secondaryColor1,
  ),
  'secondary_color_2': OpenPrintTagMainData._uint8ListToJson(
    instance.secondaryColor2,
  ),
  'secondary_color_3': OpenPrintTagMainData._uint8ListToJson(
    instance.secondaryColor3,
  ),
  'secondary_color_4': OpenPrintTagMainData._uint8ListToJson(
    instance.secondaryColor4,
  ),
  'transmission_distance': instance.transmissionDistance,
  'tags': instance.tags,
  'density': instance.density,
  'filament_diameter': instance.filamentDiameter,
  'shore_hardness_a': instance.shoreHardnessA,
  'shore_hardness_d': instance.shoreHardnessD,
  'min_nozzle_diameter': instance.minNozzleDiameter,
  'min_print_temperature': instance.minPrintTemperature,
  'max_print_temperature': instance.maxPrintTemperature,
  'preheat_temperature': instance.preheatTemperature,
  'min_bed_temperature': instance.minBedTemperature,
  'max_bed_temperature': instance.maxBedTemperature,
  'min_chamber_temperature': instance.minChamberTemperature,
  'max_chamber_temperature': instance.maxChamberTemperature,
  'chamber_temperature': instance.chamberTemperature,
  'container_width': instance.containerWidth,
  'container_outer_diameter': instance.containerOuterDiameter,
  'container_inner_diameter': instance.containerInnerDiameter,
  'container_hole_diameter': instance.containerHoleDiameter,
  'viscosity_18c': instance.viscosity18c,
  'viscosity_25c': instance.viscosity25c,
  'viscosity_40c': instance.viscosity40c,
  'viscosity_60c': instance.viscosity60c,
  'container_volumetric_capacity': instance.containerVolumetricCapacity,
  'cure_wavelength': instance.cureWavelength,
};
